name: docker release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: docker push extension
        run: |
          CHANGELOG=$(git show -s --format=%B)
          echo $CHANGELOG
          TAG=${{github.ref_name}} COMMIT=${{github.sha}} OWNER=${{github.repository_owner}} CHANGELOG=$CHANGELOG make push-extension
